BA-433 line consistency
playgroundinc/borealis-ai pull request #358
Opened 2022-05-02 15:41 UTC by Braedencraig

Create consistency between all line dividers on the site colour wise.

2022-05-02 17:31 UTC, lisafolkerson requested changes
Can you please confirm changes on page-search.php ? I think the search and replace failed there.

Also I know there was a lighter grey and a darker grey on the site. I know this makes consistent but I thought the lighter grey (200 not 500) was what had been asked for but I'm not sure I'm remembering correctly.

2022-05-02 17:31 UTC, lisafolkerson commented on web/wp-content/themes/borealis-2021/page-search.php
> +    <div class="border-b bordercolor--shade-grey-500"></div>
should this -- be  - ?

2022-05-02 17:31 UTC, lisafolkerson commented on web/wp-content/themes/borealis-2021/page-search.php
> +                        <div class="border-solid border-t bordercolor--shade-grey-500 <?php echo intval($Query->max_num_pages) > 1 ? '' : 'hidden' ?> hover:bg-primary-navy-400 hover:text-shade-white-
should this -- be  - ?

2022-05-02 17:31 UTC, lisafolkerson commented on web/wp-content/themes/borealis-2021/page-search.php
> +                                <li class="last:border-b-0 border-b bordercolor--shade-grey-500">
should this -- be  - ?

2022-05-02 17:31 UTC, lisafolkerson commented on web/wp-content/themes/borealis-2021/page-search.php
> +                        <ul class="posts-listing bordercolor--shade-grey-500 border-t" data-page="1" data-research-areas="<?php echo esc_attr(implode(',', $research_areas)) ?>" data-total="<?php echo
should this -- be  - ?

2022-05-02 17:31 UTC, lisafolkerson commented on web/wp-content/themes/borealis-2021/page-search.php
> +                                <li class="last:border-b-0 border-b bordercolor--shade-grey-500">
should this -- be  - ?

2022-05-02 17:31 UTC, lisafolkerson commented on web/wp-content/themes/borealis-2021/page-search.php
> +                        <ul class="posts-listing bordercolor--shade-grey-500 border-t" data-page="1" data-research-areas="<?php echo esc_attr(implode(',', $research_areas)) ?>" data-total="<?php echo
should this -- be  - ?

2022-05-02 17:31 UTC, lisafolkerson commented on web/wp-content/themes/borealis-2021/page-search.php
> +    <div class="border-b bordercolor--shade-grey-500"></div>
Seems like an issue this file only 👍🏻

2022-05-02 17:52 UTC, Braedencraig commented
They requested all lines to match whats currently on the homepage live https://live-borealis-ai.pantheonsite.io/ so thats why I just went with 500! @lisafolkerson

2022-05-03 13:23 UTC, lisafolkerson approved these changes
Awesome thank you!

2022-05-03 13:50 UTC, merged